api/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('register', perform_registration, name="registerapi"),
    path('login', perform_login, name="loginapi"),
    path('profile/<int:id>', user_profile, name="profileapi"),
    path('updateprofile/<int:id>', updateUserProfile, name="updateprofileapi"),
    path('user/<int:id>', get_user, name="userapi"),

    path('countrylist', country_list, name="countrylist"),
    path('statelist', state_list, name="statelist"),
    path('citylist', city_list, name="citylist"),

    path('educatlistlist', education_category_list, name="educatlistlist"),
    path('educat/<int:id>', education_category, name="educat"),

    path('edusubcatlistlist', education_sub_category_list, name="edusubcatlistlist"),
    path('edusubcat/<int:id>', education_sub_category, name="edusubcat"),
    path('edusubcatfilter/<int:id>', education_sub_category_by_cat, name="edusubcatfilter"),

    path('subjects/<int:id>', subjects_by_sub_cat, name="subjects"),

    path('edulistlist', education_list, name="edulistlist"),
    path('edu/<int:id>', education, name="edu"),
    path('edufiltercat/<int:id>', education_by_cat, name="edufiltercat"),
    path('edufiltersubcat/<int:id>', education_by_sub_cat, name="edufiltersubcat"),
    path('edubysubjects/<int:id>', edu_by_subjects, name="edubysubjects"),

    path('newscatlist', newscat_list, name="newscatlistapi"),
    path('newscat/<int:id>', newscat, name="newscatapi"),

    path('newslist', news_list, name="newslistapi"),
    path('news/<int:id>', news, name="newsapi"),

    path('sendotp', perform_otp_sms, name="sendotp"),
]

bhimbakend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    # path('', include('home.urls')),
    path('', include('website.urls')),
    path('api/', include('api.urls')),
    path('admin/', include('myadmin.urls')),
    path('social-auth/',include('social_django.urls',namespace='social')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

website/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index, name="index"),
    path('about/', views.aboutus, name="about"),
    path('course-list/', views.courses, name="course-list"),
    path('course-details/<int:id>', views.courses_details, name="course-details"),
    path('teachers-list/', views.teachers, name="teachers-list"),
    path('teachers-details/<int:id>', views.teachers_details, name="teachers-details"),
    path('news/', views.news, name="news-list"),
    path('singlenews/<int:id>', views.news_details, name="news-detail"), #panding
    path('blog/', views.blog, name="blog-list"),
    path('singleblog/<int:id>', views.blog_details, name="blog-detail"), #panding
    path('ebooks/', views.shop, name="ebooks-list"),
    path('singleebook/<int:id>', views.ebook_details, name="ebooks-detail"),
    path('contact/', views.contactus, name="contact"),
    path('post-contact/', views.post_contacts, name="post-contact"),

    path('register/',views.register,name='register'),
    path('login/',views.user_login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('profile/',views.edit,name='user-profile'),

    path('tc/',views.terms_conditions_view,name='tc'),
    path('privecy/',views.privecy_policy_view,name='privecy'),

    path('edcat/',views.load_sub_category,name='edcat-ajax'),
    path('sub/',views.load_subjects,name='sub-ajax'),
    path('subject-ajax/',views.load_chapters,name='subject-ajax'),

    path('gallery/',views.gallery,name='gallery-view'),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
import datetime
from embed_video.fields import EmbedVideoField
from myadmin.models import *

class Country(models.Model):
    country_name = models.CharField(max_length=150, default="")
    active = models.BooleanField(default=True)
    created_at = models.DateField(default=datetime.datetime.now)
    updated_at = models.DateField(default=datetime.datetime.now) 

    def __str__(self):
        return self.country_name

class State(models.Model):
    state_name = models.CharField(max_length=150, default="")
    active = models.BooleanField(default=True)
    created_at = models.DateField(default=datetime.datetime.now)
    updated_at = models.DateField(default=datetime.datetime.now)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    def __str__(self):
        return self.state_name

class City(models.Model):
    city_name = models.CharField(max_length=150, default="")
    active = models.BooleanField(default=True)
    created_at = models.DateField(default=datetime.datetime.now)
    updated_at = models.DateField(default=datetime.datetime.now)
    state = models.ForeignKey(State, on_delete=models.CASCADE)

    def __str__(self):
        return self.city_name

class Block(models.Model):
    block_name = models.CharField(max_length=150, default="")
    active = models.BooleanField(default=True)
    created_at = models.DateField(default=datetime.datetime.now)
    updated_at = models.DateField(default=datetime.datetime.now)
    city = models.ForeignKey(City, on_delete=models.CASCADE)

    def __str__(self):
        return self.block_name

class Village(models.Model):
    village_name = models.CharField(max_length=150, default="")
    active = models.BooleanField(default=True)
    created_at = models.DateField(default=datetime.datetime.now)
    updated_at = models.DateField(default=datetime.datetime.now)
    block = models.ForeignKey(Block, on_delete=models.CASCADE)

    def __str__(self):
        return self.village_name

class Degree(models.Model):
    degree_name = models.CharField(max_length=200, default="")
    active = models.BooleanField(default=True)
    created_at = models.DateField(default=datetime.datetime.now)
    updated_at = models.DateField(default=datetime.datetime.now)

    def __str__(self):
        return self.degree_name

class CustomUser(models.Model):
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    email = models.CharField(max_length=150, blank=True, null=True)
    phone = models.CharField(max_length=15, unique=True)
    active = models.BooleanField(default=True)
    joined_date = models.DateTimeField(default=datetime.datetime.today)

    @staticmethod
    def get_user_by_phone(phone):
        try:
            return CustomUser.objects.get(phone=phone)
        except:
            return False

    @staticmethod
    def get_user_by_id(id):
        try:
            return CustomUser.objects.get(id=id)
        except:
            return False

class Profile(models.Model):
    GENDER_CHOICES = [
        ('male', 'Male'),
        ('female', 'Female')
    ]

    PROFESSION_CHOICES = [
        ('Student', 'Student'),
        ('Profession', 'Profession'),
        ('Business', 'Business'),
        ('Government Servant', 'Government Servant'),
        ('Social Worker', 'Social Worker'),
        ('Private Job', 'Private Job')
    ]

    user = models.OneToOneField(User ,on_delete=models.CASCADE)
    phone = models.CharField(max_length=15, unique=True, null=True, blank=True)
    intrests = models.CharField(max_length=255, default="",blank=True, null=True)
    date_of_birth = models.CharField(blank=True,null=True, default="", max_length=255)
    photo = models.ImageField(upload_to='users/', blank=True, null=True)
    gender = models.CharField(max_length=15, default="", choices=GENDER_CHOICES, blank=True, null=True)
    street1 = models.CharField(max_length=200, blank=True, null=True, default="")
    street2 = models.CharField(max_length=200, blank=True, null=True, default="")
    country = models.CharField(max_length=255, default="", blank=True, null=True, verbose_name="Enter Country")
    add_state = models.CharField(max_length=255, default="", blank=True, null=True, verbose_name="Enter State")
    add_city = models.CharField(max_length=255, default="", blank=True, null=True, verbose_name="Enter Taluka")
    add_block = models.CharField(max_length=255, default="", blank=True, null=True, verbose_name="Enter City")
    add_village = models.CharField(max_length=255, default="", blank=True, null=True, verbose_name="Enter Village")
    add_international = models.TextField(blank=True, null=True, verbose_name="International Address")
    degree = models.CharField(max_length=255, default="", blank=True, null=True, verbose_name="Enter Degree")
    profession_type = models.CharField(max_length=150, default="", blank=True, null=True, choices=PROFESSION_CHOICES)
    title = models.CharField(max_length=255, blank=True, null=True, verbose_name="Profession Details")
    created_at = models.DateField(default=datetime.datetime.now, blank=True, null=True)
    updated_at = models.DateField(default=datetime.datetime.now, blank=True, null=True)

    def __str__(self):
        return f'Profile for user {self.user.username}'

class NewsCategory(models.Model):
    category_name = models.CharField(max_length=255, default="")
    active = models.BooleanField(default=True)
    created_at = models.DateField(default=datetime.datetime.now)
    updated_at = models.DateField(default=datetime.datetime.now)

    def __str__(self):
        return self.category_name

    @staticmethod
    def get_all_categories():
        return NewsCategory.objects.all()

    @staticmethod
    def get_category_by_id(id):
        return NewsCategory.objects.get(id=id)

    @staticmethod
    def get_category_by_active():
        return NewsCategory.objects.filter(active=True)

class BlogCategory(models.Model):
    category_name = models.CharField(max_length=255, default="")
    active = models.BooleanField(default=True)
    created_at = models.DateField(default=datetime.datetime.now)
    updated_at = models.DateField(default=datetime.datetime.now)


    def __str__(self):
        return self.category_name


    @staticmethod
    def get_all_categories():
        return BlogCategory.objects.all()

    @staticmethod
    def get_category_by_id(id):
        return BlogCategory.objects.get(id=id)

    @staticmethod
    def get_category_by_active():
        return BlogCategory.objects.filter(active=True)

class News(models.Model):
    title = models.CharField(max_length=255, default="")
    description = RichTextField(blank=True, null=True)
    image = models.ImageField(upload_to='news/', default="", blank=True, null=True)
    youtube_link = EmbedVideoField(default="", blank=True, null=True)
    active = models.BooleanField(default=True)
    category = models.ForeignKey(NewsCategory, on_delete=models.CASCADE, default="")
    news_date = models.DateField(default=datetime.datetime.now)
    created_at = models.DateField(default=datetime.datetime.now)
    updated_at = models.DateField(default=datetime.datetime.now)

    def __str__(self):
        return self.title

    @staticmethod
    def get_all_news():
        return News.objects.all()

    @staticmethod
    def news_count():
        return News.objects.all().count()

    @staticmethod
    def get_news_by_id(id):
        return News.objects.get(id=id)

    @staticmethod
    def get_news_by_active():
        return News.objects.filter(active=True)

class Blog(models.Model):
    title = models.CharField(max_length=255, default="")
    description = RichTextField(blank=True, null=True)
    image = models.ImageField(upload_to='blog/', default="", blank=True, null=True)
    youtube_link = EmbedVideoField(default="", blank=True, null=True)
    active = models.BooleanField(default=True)
    category = models.ForeignKey(BlogCategory, on_delete=models.CASCADE, default="")
    blog_date = models.DateField(default=datetime.datetime.now)
    created_at = models.DateField(default=datetime.datetime.now)
    updated_at = models.DateField(default=datetime.datetime.now)

    def __str__(self):
        return self.title

    @staticmethod
    def get_all_blog():
        return Blog.objects.all()
    
    @staticmethod
    def blog_count():
        return Blog.objects.all().count()

    @staticmethod
    def get_blog_by_id(id):
        return Blog.objects.get(id=id)

    @staticmethod
    def get_blog_by_active():
        return Blog.objects.filter(active=True)

class EducationCategory(models.Model):
    category_name = models.CharField(max_length=255, default="")
    photo = models.ImageField(upload_to='educattion/', default="", blank=True, null=True)
    active = models.BooleanField(default=True)
    created_at = models.DateField(default=datetime.datetime.now)
    updated_at = models.DateField(default=datetime.datetime.now)

    def __str__(self):
        return self.category_name

    @staticmethod
    def get_all_categories():
        return EducationCategory.objects.all()

    @staticmethod
    def get_category_by_id(id):
        return EducationCategory.objects.get(id=id)

    @staticmethod
    def get_category_by_active():
        return EducationCategory.objects.filter(active=True)

class EducationSubCategory(models.Model):
    category_name = models.CharField(max_length=255, default="")
    image = models.ImageField(upload_to='educattion/', default="",  blank=True, null=True)
    active = models.BooleanField(default=True)
    category = models.ForeignKey(EducationCategory, on_delete=models.CASCADE, default="", null=True, blank=True)
    created_at = models.DateField(default=datetime.datetime.now)
    updated_at = models.DateField(default=datetime.datetime.now)

    def __str__(self):
        return self.category_name

    @staticmethod

website/models.py
from django.db import models

# Create your models here.

myadmin/views/login.py
from django.shortcuts import render, redirect, HttpResponse, HttpResponseRedirect
from myadmin.forms import LoginForm
from django.contrib import messages
from django.contrib.auth import authenticate,login

def admin_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,username=cd['username'],
                                      password=cd['password'])
            if user is not None:
                if user.is_active and user.is_staff:
                    login(request,user)
                    return redirect("dashboard_admin")
                else:
                    messages.error(request, "Disabled Account!")
                    return redirect("adminLogin")
            else:
                messages.error(request, "Invalid login!")
                return redirect("adminLogin")
    else:
        form=LoginForm()
    return render(request,'myadmin/login.html',{'form':form})

def logout(request):
    request.session.clear()
    return redirect('adminLogin')

website/templates/website/aboutus.html
{% extends 'website/base.html' %}
{% load static %}
{% block title %} About Us - Bim Connect {% endblock %}
{% block content %}

<!--Breadcrumb Banner Area Start-->
<div class="breadcrumb-banner-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumb-text">
                    <h1 class="text-center">ABOUT US</h1>
                    <div class="breadcrumb-bar">
                        <ul class="breadcrumb">
                            <li><a href="{% url 'index' %}">Home</a></li>
                            <li>ABOUT US</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--End of Breadcrumb Banner Area-->
<!--About Page Area Start-->
<div class="about-page-area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title-wrapper">
                    <div class="section-title">
                        <h3>Who we are</h3>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="about-text-container">
                    <h3>{{aboutus.title1}}</h3>
                    <p>{{aboutus.description1|safe}}</p>  
                    <h3>{{aboutus.mission_title}}</h3>
                    <p>{{aboutus.mission_description|safe}}</p>
                </div>
            </div>
            <div class="col-md-6">
                <div class="skill-image">
                    {% if aboutus.image %}
                    <img src="{{aboutus.image.url}}" alt="" width="3650px" height="2681px">
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
<!--End of About Page Area-->

{% endblock %}

website/templates/website/blog_details.html
{% extends 'website/base.html' %}
{% block meta %} 
<meta property="og:title" content="{{blog.title}}" />
<meta property="og:image" content="{{blog.image.url}}">
{% endblock %}
{% load static %}
{% block title %} Blog - Bim Connect {% endblock %}
{% block content %}
{% load social_share %}

<!--Breadcrumb Banner Area Start-->
<div class="breadcrumb-banner-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumb-text">
                    <h1 class="text-center">Single Blog</h1>
                    <div class="breadcrumb-bar">
                        <ul class="breadcrumb">
                            <li><a href="{% url 'index' %}">Home</a></li>
                            <li><a href="{% url 'blog-list' %}">Blog</a></li>
                            <li>Single Blog</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--End of Breadcrumb Banner Area-->

<!--News Details Area Start-->
<div class="news-details-area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-md-8">
                <div class="news-details-content">
                   <div class="single-latest-item">
                        {% if blog.image %}
                        <img src="{{blog.image.url}}" alt="" width="870px" height="439px">  
                        {% endif %} 
                        <div class="single-latest-text">
                            <h3>Learn English in ease simply random text</h3> 
                            <div class="single-item-comment-view">
                                <span><i class="zmdi zmdi-calendar-check"></i>{{blog.blog_date}}</span>
                                <span><i class="zmdi zmdi-folder"></i>{{blog.category}}</span>
                            </div>
                            <p>{{blog.description|safe}}</p>
                            <div class="tags-and-links">
                                <div class="social-links">
                                    <span>
                                        {% post_to_facebook object_or_url "Share on Facebook" "btn btn-primary btn-sm fa fa-facebook" %}
                                    </span>
                                    <span>
                                        {% post_to_whatsapp object_or_url "Share on WhatsApp" "btn btn-success btn-sm fa fa-whatsapp" %}
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>    
            </div>
            <div class="col-lg-3 col-md-4">
                <div class="sidebar-widget">
                    <div class="single-sidebar-widget">
                        <h4 class="title">Recent Posts</h4>
                        <div class="recent-content">
                            {% for n in related_blog %}
                            <div class="recent-content-item">
                                {% if n.image %}
                                <a href="#"><img src="{{n.image.url}}" alt="" width="70px" height="67px"></a>
                                {% endif %}
                                <div class="recent-text">
                                    <h4><a href="{% url 'news-detail' n.id %}">{{n.title}}</a></h4>
                                    <div class="single-item-comment-view">
                                        <span><i class="zmdi zmdi-folder"></i>{{n.category}}</span>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--End of News Details Area-->

{% endblock %}

website/templates/website/courses.html
{% extends 'website/base.html' %}
{% load static %}
{% block title %} Courses - Bim Connect {% endblock %}
{% block content %}

<!--Breadcrumb Banner Area Start-->
<div class="breadcrumb-banner-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumb-text">
                    <h1 class="text-center">Courses</h1>
                    <div class="breadcrumb-bar">
                        <ul class="breadcrumb">
                            <li><a href="{% url 'index' %}">Home</a></li>
                            <li>Courses</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--End of Breadcrumb Banner Area-->

<div class="search-category">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-md-offset-1">
                <form action="{% url 'course-list' %}" method="post">
                    {% csrf_token %}
                    <div class="form-container">
                        <div class="box-select">
                            <div class="select large">
                                <select name="category" id="category" data-educat="{% url 'edcat-ajax' %}">
                                    <option value="0">Select Category</option>
                                    {% for i in categories %}
                                    <option value="{{i.id}}">{{i.category_name}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="select small">
                                <select name="subcategory" id="subcategory" data-sub="{% url 'sub-ajax' %}">
                                    <option value="0">=================</option>
                                </select>
                            </div>
                            <div class="select medium">
                                <select name="subject" id="subject" data-subject="{% url 'subject-ajax' %}">
                                    <option value="0">=================</option>
                                </select>
                            </div>
                            <div class="select medium">
                                <select name="chapter" id="chapter">
                                    <option value="0">=================</option>
                                </select>
                            </div>
                        </div>
                        <button type="submit" style="margin-top: 20px; float:left;">Search Course</button>
                    </div>
                </form>  
            </div>
        </div>
    </div>
</div>
<!--Course Area Start-->
<div class="course-area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title-wrapper">
                    <div class="section-title">
                        <h3>OUR COURSES</h3>
                        <p>There are many types of Courses</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            {% for i in all_edu %}
            <div class="col-md-4 col-sm-6">
                <div class="single-item">
                    <div class="single-item-image overlay-effect">
                        <a href="{% url 'course-details' i.id %}">
                            {% if i.image %}
                            <img src="{{i.image.url}}" alt="" width="300px" height="211px">
                            {% endif %}
                        </a>
                    </div>
                    <div class="single-item-text">
                        <h5><a href="{% url 'course-details' i.id %}">{{i.title}}</a></h5>
                        <div class="single-item-text-info">
                            <span>By:</span> <span>{{i.teacher}}</span>
                            <span>Subject:</span> <span>{{i.subject}}</span>
                        </div>
                        <div class="single-item-text-info">
                            <span>Sub Category:</span> <span>{{i.sub_category}}</span><br>
                            <span>Category:</span> <span>{{i.category}}</span>
                        </div>
                        <p>{{i.description|safe|slice:"40"}}...</p>  
                    </div>
                    <div class="button-bottom">
                        <a href="{% url 'course-details' i.id %}" class="button-default">Learn Now</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<!--End of Course Area-->

{% endblock %}

{% block customjs %} 
<script>
    $(document).ready(function() {
        $('#category').change(function(){
            const url = $("#category").attr("data-educat");
            console.log(url);
            const educatId = $(this).val();
            console.log(educatId);

            if(educatId != null){
                $.ajax({                       // initialize an AJAX request
                    url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
                    data: {
                        'educatId': educatId       // add the country id to the GET parameters
                    },
                    success: function (data) {   // `data` is the return of the `load_cities` view function
                        //$("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
                    

                        let html_data = '<option value="0">=================</option>';
                        data.forEach(function (edusubcat) {
                            html_data += `<option value="${edusubcat.id}">${edusubcat.category_name}</option>`
                        });
                        console.log(html_data);
                        $("#subcategory").html(html_data);

                    }
                });
            } else {
                $("#subcategory").html('<option value="0">=================</option>');
            }
        });

        $('#subcategory').change(function(){
            const url = $("#subcategory").attr("data-sub");
            console.log(url);
            const edusubid = $(this).val();
            console.log(edusubid);

            if(edusubid != null){
                $.ajax({                       // initialize an AJAX request
                    url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
                    data: {
                        'edusubid': edusubid       // add the country id to the GET parameters
                    },
                    success: function (data) {   // `data` is the return of the `load_cities` view function
                        //$("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
                    

                        let html_data = '<option value="0">=================</option>';
                        data.forEach(function (edusubcat) {
                            html_data += `<option value="${edusubcat.id}">${edusubcat.subject_name}</option>`
                        });
                        console.log(html_data);
                        $("#subject").html(html_data);

                    }
                });
            } else {
                $("#subject").html('<option value="0">=================</option>');
            }
        });

        $('#subject').change(function () {
            const url = $("#subject").attr("data-subject");
            console.log(url);
            const edusubjectid = $(this).val();
            console.log(edusubjectid);

            if (edusubjectid != null) {
                $.ajax({                       // initialize an AJAX request
                    url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
                    data: {
                        'edusubjectid': edusubjectid       // add the country id to the GET parameters
                    },
                    success: function (data) {   // `data` is the return of the `load_cities` view function
                        //$("#id_city").html(data);  // replace the contents of the city input with the data that came from the server


                        let html_data = '<option value="0">=================</option>';
                        data.forEach(function (edusubcat) {
                            html_data += `<option value="${edusubcat.id}">${edusubcat.chapter_name}</option>`
                        });
                        console.log(html_data);
                        $("#chapter").html(html_data);

                    }
                });
            } else {
                $("#chapter").html('<option value="0">=================</option>');
            }
        });
    });
</script>
{% endblock %}

website/templates/website/login.html
{% extends 'website/base.html' %}
{% load static %}
{% block title %} Login - Bim Connect {% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="row text-center">
    <div class="col-lg-12 col-md-12 col-sm-12">
      {% if flag == 'success' %}
      <span class="alert alert-success">{{msg}}</span>
      {% elif flag == 'error' %}
      <span class="alert alert-danger">{{msg}}</span>
      {% endif %}
    </div>
</div>
<div class="row" style="margin-top: 8pt; padding: 50pt;">
    <div class="col-lg-6 col-md-6 col-sm-6 col-lg-offset-3 col-md-offset-1 col-sm-offset-1">
        <form action="" method="post">
            <div class="panel panel-default" style="padding: 5pt;">
                <div class="panel-header">
                    <h2 class="text-center">Login Here</h2>
                </div>
                <div class="panel-body">
                    {{ login_form|crispy }}
                    {% csrf_token %}
                </div>
                <div class="panel-footer">
                    <button class="btn btn-success btn-lg btn-block mt-15" type="submit" style="background-color: #86BC42;">Login</button>
                    <a href="{% url 'register' %}" class="btn btn-link btn-lg btn-block mt-15" type="submit">Don`t have an account ? Register</a>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}